#!/bin/bash

python<<EOF
import numpy as np
import matplotlib
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['text.latex.unicode'] = True
import matplotlib.pyplot as plt
from matplotlib import colors, ticker, cm
import linecache
from PIL import Image

#Time reading
time = float(linecache.getline("DATA_$1_2D.dat",2))

#Data reading
xx, yy, n, p, u, v = np.loadtxt("DATA_$1_2D.dat",skiprows=3,unpack=True)

xxneg = -xx

l = len(xx)
l = np.sqrt(l)
l = int(l)

n = n.reshape(161,401)
n = n.T

p = p.reshape(161,401)
p = p.T

u = u.reshape(161,401)
u = u.T

v = v.reshape(161,401)
v = v.T

nx = np.linspace(np.min(xx), np.max(xx), 161)
ny = np.linspace(np.min(yy), np.max(yy), 401)
X,Y = np.meshgrid(nx,ny)

plt.rc('font', family='serif')
plt.rc('text', usetex=True)

plt.figure(figsize=(8,6),dpi=100)
plt.xlabel(r'\$r\$',fontsize=12)
plt.ylabel(r'\$z\$',fontsize=12)
plt.title(r'Time = %.2f s'%time,fontsize=12)

#Logaritmic linspace
levels = np.linspace(-2.0,2.0,400)

#Linear linspace
#levels = np.linspace(0.0,30.0,400)

#Space between vectors
qx = 5
qy = 5

#Heat Colour - Axisymmetric
#cn = plt.contourf(X,Y,np.log10(n),levels=levels,cmap=plt.cm.gist_heat)
#cn = plt.contourf(-X,Y,np.log10(n),levels=levels,cmap=plt.cm.gist_heat)

#Jet Colour - Axisymmetric
cn = plt.contourf(X,Y,np.log10(n),levels=levels,cmap=plt.cm.afmhot)
cn = plt.contourf(-X,Y,np.log10(n),levels=levels,cmap=plt.cm.afmhot)

#Vertical colorbar
cbarn = plt.colorbar(cn, format="%.2f")
cbarn.set_label(r'Density \$\log \rho\$',rotation=270,fontsize=12,labelpad=20)

#Horizontal colorbar
#cbarn = plt.colorbar(cn, format="%.2f",orientation='horizontal')
#cbarn.set_label(r'Density \$\log \rho\$',fontsize=12,labelpad=20)

#Vector plotting
#uut= u/np.sqrt(u**2 + v**2)
#vvt= v/np.sqrt(u**2 + v**2)
#uu = np.nan_to_num(uut)
#vv = np.nan_to_num(vvt)
#plt.quiver(X[::qx,::qy],Y[::qx,::qy],uu[::qx,::qy],vv[::qx,::qy],np.sqrt(uu[::qx,::qy]**2.0 + vv[::qx,::qy]**2.0),
#		  units='width',scale=40.5)#,cmap='Reds')
#plt.quiver(-X[::qx,::qy],Y[::qx,::qy],-uu[::qx,::qy],vv[::qx,::qy],np.sqrt(uu[::qx,::qy]**2.0 + vv[::qx,::qy]**2.0),
#		  units='width',scale=40.5)#,cmap='Reds')

#Rectangular graph
plt.axes().set_aspect('equal')

#Graph name
plt.savefig("N$2_py.png",dpi=100,bbox_inches="tight")
#plt.show()
plt.close()

EOF
