#!/bin/bash

python<<EOF
import numpy as np
import matplotlib
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['text.latex.unicode'] = True
import matplotlib.pyplot as plt
from matplotlib import colors, ticker, cm
import linecache
from PIL import Image

#Time reading
time = float(linecache.getline("DATA_$1_1D.dat",2))

#Data reading
xx, n, p, u = np.loadtxt("DATA_$1_1D.dat",skiprows=3,unpack=True)

plt.rc('font', family='serif')
plt.rc('text', usetex=True)

plt.figure(figsize=(8,6),dpi=100)
plt.xlabel(r'\$r\$',fontsize=12)
plt.ylabel(r'\$n\$',fontsize=12)
plt.title(r'Time = %.2f s'%time,fontsize=12)

plt.axis([np.min(xx),np.max(xx),np.min(n),np.max(n)])
plt.plot(xx,n,'o',markersize=1)

#Graph name
plt.savefig("N$2_py.png")
plt.close()

#levels = np.linspace(np.min(u),np.max(np.abs(u)),400)

#cn = plt.contourf(X,Y,(u),interpolation='sinc',levels=levels,cmap=plt.cm.gist_heat)
#cbarn = plt.colorbar(cn, format="%.2f")
#cbarn.set_label(r'Velocity \$v_x\$',rotation=270,fontsize=12,labelpad=20)
#plt.savefig("Vx$1_py.png")
#plt.close()

#levels = np.linspace(np.min(v),np.max(np.abs(v)),400)
#
#cn = plt.contourf(X,Y,(v),interpolation='sinc',levels=levels,cmap=plt.cm.gist_heat)
#cbarn = plt.colorbar(cn, format="%.2f")
#cbarn.set_label(r'Velocity \$v_y\$',rotation=270,fontsize=12,labelpad=20)
#plt.savefig("Vy$1_py.png")
#plt.close()

#plt.figure(figsize=(8,6),dpi=100)
#levels = np.linspace(0,np.max(np.abs(p)),400)

#cp = plt.contourf(X,Y,p,interpolation='bicubic',levels=levels,cmap=plt.cm.gist_heat)
#cbarp = plt.colorbar(cp, format="%.2e")
#cbarp.set_label(r'Pressure \$p\$',rotation=270,fontsize=12,labelpad=20)
#plt.savefig("P$2_py.png")
#plt.close()

#levels = np.linspace(0,np.max(np.abs(u)),400)

#cu = plt.contourf(X,Y,np.abs(u),interpolation='sinc',levels=levels,cmap=plt.cm.YlOrBr)
#cbaru = plt.colorbar(cu, format="%.2f")
#cbaru.set_label(r'Velocity \$v_x\$',rotation=270,fontsize=12,labelpad=20)
#plt.savefig("Vx$1_py.png")
#plt.close()
#
#levels = np.linspace(0,np.max(np.abs(v)),400)
#
#cv = plt.contourf(X,Y,np.abs(v),interpolation='bicubic',levels=levels,cmap=plt.cm.hot)
#cbarv = plt.colorbar(cv, format="%.2f")
#cbarv.set_label(r'Velocity \$v_y\$',rotation=270,fontsize=12,labelpad=20)
#plt.savefig("Vy$1_py.png")
#plt.close()
#

#im = Image.open("N$2_py.png")
#im = im.crop((200,0,780,600))
#im.save("N$2_py.png")

EOF
