#!/bin/bash

python<<EOF
import numpy as np
import matplotlib
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['text.latex.unicode'] = True
import matplotlib.pyplot as plt
from matplotlib import colors, ticker, cm
import linecache
from PIL import Image

#Time reading
time = float(linecache.getline("DATA_$1_1D.dat",2))

#Data reading
r, n, p, u = np.loadtxt("DATA_$1_1D.dat",skiprows=3,unpack=True)

N = np.array([n,]*2601)

plt.rc('font', family='serif')
plt.rc('text', usetex=True)

plt.figure(figsize=(8,6),dpi=100)
plt.title(r'Time = %.2f s'%time,fontsize=12)

azm = np.linspace(0,2 * np.pi,2601)
R, th = np.meshgrid(r,azm)
z = R**2.0

plt.subplot(projection='polar')
plt.pcolormesh(th,R,N)
plt.colorbar(label='Density n')

plt.plot(azm,r,ls='none')
plt.grid()

#Graph name
plt.savefig("N$2_py.png")
plt.close()

EOF
